package com.vani.webapp.models;
// Generated 29 May, 2017 12:02:51 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "attendance")
public class Division implements java.io.Serializable {

	private int id;
	private Integer version;
	private SchoolClass schoolClass;
	private User user;
	private String division;
	private Date createdTimeStamp;
	private Set<Student> students = new HashSet<Student>(0);

	public Division() {
	}

	public Division(int id, SchoolClass schoolClass, User user, String division, Date createdTimeStamp) {
		this.id = id;
		this.schoolClass = schoolClass;
		this.user = user;
		this.division = division;
		this.createdTimeStamp = createdTimeStamp;
	}

	public Division(int id, SchoolClass schoolClass, User user, String division, Date createdTimeStamp,
			Set<Student> students) {
		this.id = id;
		this.schoolClass = schoolClass;
		this.user = user;
		this.division = division;
		this.createdTimeStamp = createdTimeStamp;
		this.students = students;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false)
	public SchoolClass getSchoolClass() {
		return this.schoolClass;
	}

	public void setSchoolClass(SchoolClass schoolClass) {
		this.schoolClass = schoolClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "division", nullable = false, length = 45)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time_stamp", nullable = false, length = 19)
	public Date getCreatedTimeStamp() {
		return this.createdTimeStamp;
	}

	public void setCreatedTimeStamp(Date createdTimeStamp) {
		this.createdTimeStamp = createdTimeStamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "division")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
