package com.vani.webapp.models;
// Generated 2 Jun, 2017 4:27:33 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SchoolClass generated by hbm2java
 */
@Entity
@Table(name = "school_class", catalog = "attendance")
public class SchoolClass implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private School school;
	private String className;
	private Date createdTimeStamp;
	private Set<Division> divisions = new HashSet<Division>(0);

	public SchoolClass() {
	}

	public SchoolClass(School school, String className, Date createdTimeStamp) {
		this.school = school;
		this.className = className;
		this.createdTimeStamp = createdTimeStamp;
	}

	public SchoolClass(School school, String className, Date createdTimeStamp, Set<Division> divisions) {
		this.school = school;
		this.className = className;
		this.createdTimeStamp = createdTimeStamp;
		this.divisions = divisions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_id", nullable = false)
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "class_name", nullable = false, length = 45)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time_stamp", nullable = false, length = 19)
	public Date getCreatedTimeStamp() {
		return this.createdTimeStamp;
	}

	public void setCreatedTimeStamp(Date createdTimeStamp) {
		this.createdTimeStamp = createdTimeStamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schoolClass")
	public Set<Division> getDivisions() {
		return this.divisions;
	}

	public void setDivisions(Set<Division> divisions) {
		this.divisions = divisions;
	}

}
