package com.vani.webapp.models;
// Generated 2 Jun, 2017 4:27:33 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "school", catalog = "attendance")
public class School implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private String schoolName;
	private String address;
	private String phone;
	private Date createdTimeStamp;
	private Set<SchoolClass> schoolClasses = new HashSet<SchoolClass>(0);

	public School() {
	}

	public School(String schoolName, String address, String phone, Date createdTimeStamp) {
		this.schoolName = schoolName;
		this.address = address;
		this.phone = phone;
		this.createdTimeStamp = createdTimeStamp;
	}

	public School(String schoolName, String address, String phone, Date createdTimeStamp,
			Set<SchoolClass> schoolClasses) {
		this.schoolName = schoolName;
		this.address = address;
		this.phone = phone;
		this.createdTimeStamp = createdTimeStamp;
		this.schoolClasses = schoolClasses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "school_name", nullable = false, length = 45)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	@Column(name = "address", nullable = false, length = 16777215)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", nullable = false, length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time_stamp", nullable = false, length = 19)
	public Date getCreatedTimeStamp() {
		return this.createdTimeStamp;
	}

	public void setCreatedTimeStamp(Date createdTimeStamp) {
		this.createdTimeStamp = createdTimeStamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "school")
	public Set<SchoolClass> getSchoolClasses() {
		return this.schoolClasses;
	}

	public void setSchoolClasses(Set<SchoolClass> schoolClasses) {
		this.schoolClasses = schoolClasses;
	}

}
