package com.vani.webapp.models;
// Generated 29 May, 2017 12:02:51 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "attendance")
public class Student implements java.io.Serializable {

	private int id;
	private Integer version;
	private Division division;
	private User user;
	private String studentName;
	private int presentOrNot;
	private Date createdTimeStamp;

	public Student() {
	}

	public Student(int id, Division division, User user, String studentName, int presentOrNot) {
		this.id = id;
		this.division = division;
		this.user = user;
		this.studentName = studentName;
		this.presentOrNot = presentOrNot;
	}

	public Student(int id, Division division, User user, String studentName, int presentOrNot, Date createdTimeStamp) {
		this.id = id;
		this.division = division;
		this.user = user;
		this.studentName = studentName;
		this.presentOrNot = presentOrNot;
		this.createdTimeStamp = createdTimeStamp;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "division_id", nullable = false)
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "student_name", nullable = false, length = 45)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "PresentOrNot", nullable = false)
	public int getPresentOrNot() {
		return this.presentOrNot;
	}

	public void setPresentOrNot(int presentOrNot) {
		this.presentOrNot = presentOrNot;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time_stamp", length = 19)
	public Date getCreatedTimeStamp() {
		return this.createdTimeStamp;
	}

	public void setCreatedTimeStamp(Date createdTimeStamp) {
		this.createdTimeStamp = createdTimeStamp;
	}

}
