package com.vani.webapp.models;
// Generated 2 Jun, 2017 4:27:33 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "attendance")
public class Student implements java.io.Serializable {

	private Integer id;
	private Integer version;
	private Division division;
	private Role role;
	private User user;
	private String studentName;
	private int presentOrNot;
	private Date createdTimeStamp;
	private Set<Attendance> attendances = new HashSet<Attendance>(0);

	public Student() {
	}

	public Student(Division division, User user, String studentName, int presentOrNot) {
		this.division = division;
		this.user = user;
		this.studentName = studentName;
		this.presentOrNot = presentOrNot;
	}

	public Student(Division division, Role role, User user, String studentName, int presentOrNot, Date createdTimeStamp,
			Set<Attendance> attendances) {
		this.division = division;
		this.role = role;
		this.user = user;
		this.studentName = studentName;
		this.presentOrNot = presentOrNot;
		this.createdTimeStamp = createdTimeStamp;
		this.attendances = attendances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "division_id", nullable = false)
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "student_name", nullable = false, length = 45)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "PresentOrNot", nullable = false)
	public int getPresentOrNot() {
		return this.presentOrNot;
	}

	public void setPresentOrNot(int presentOrNot) {
		this.presentOrNot = presentOrNot;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time_stamp", length = 19)
	public Date getCreatedTimeStamp() {
		return this.createdTimeStamp;
	}

	public void setCreatedTimeStamp(Date createdTimeStamp) {
		this.createdTimeStamp = createdTimeStamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<Attendance> getAttendances() {
		return this.attendances;
	}

	public void setAttendances(Set<Attendance> attendances) {
		this.attendances = attendances;
	}

}
