package com.vani.webapp.models;
// Generated 29 May, 2017 12:02:51 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "attendance")
public class User implements java.io.Serializable {

	private int id;
	private Integer version;
	private Roles roles;
	private String email;
	private String phoneNumber;
	private Date createdTimeStamp;
	private String password;
	private String fullName;
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Division> divisions = new HashSet<Division>(0);

	public User() {
	}

	public User(int id, String email, String phoneNumber, Date createdTimeStamp, String password) {
		this.id = id;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.createdTimeStamp = createdTimeStamp;
		this.password = password;
	}

	public User(int id, Roles roles, String email, String phoneNumber, Date createdTimeStamp, String password,
				String fullName, Set<Student> students, Set<Division> divisions) {
		this.id = id;
		this.roles = roles;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.createdTimeStamp = createdTimeStamp;
		this.password = password;
		this.fullName = fullName;
		this.students = students;
		this.divisions = divisions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", nullable = false, length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time_stamp", nullable = false, length = 19)
	public Date getCreatedTimeStamp() {
		return this.createdTimeStamp;
	}

	public void setCreatedTimeStamp(Date createdTimeStamp) {
		this.createdTimeStamp = createdTimeStamp;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "full_name", length = 100)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Division> getDivisions() {
		return this.divisions;
	}

	public void setDivisions(Set<Division> divisions) {
		this.divisions = divisions;
	}

}
